version: '3.8'

services:
  ubs-risk-evaluator:
    image: ubs-risk-evaluator:latest
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./Local/:/app/data
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    ports:
      - "8080:80"